export const productsData = [
  {
    name: "Áo khoác da nam",
    category: "Thời trang nam",
    brand: "Zara",
    price: 89.99,
    desc: "Áo khoác da nam thời trang từ Zara.",
    imageURL:
      "https://i.pinimg.com/736x/5d/16/e7/5d16e706d4b64c00b0d78b61191b0239.jpg",
    rating: 4.5,
    stock: 50,
    color: "Đen",
    size: "M",
  },
  {
    name: "Váy maxi hoa",
    category: "Thời trang nữ",
    brand: "H&M",
    price: 59.99,
    desc: "Váy maxi hoa dễ thương từ H&M.",
    imageURL:
      "https://i.pinimg.com/564x/dd/e3/fe/dde3fe7c0a6a8f95a4428046f89891b8.jpg",
    rating: 4.2,
    stock: 40,
    color: "Xanh lá cây",
    size: "S",
  },
  {
    name: "Quần bò nam",
    category: "Thời trang nam",
    brand: "Levi's",
    price: 69.99,
    desc: "Quần bò nam phong cách từ Levi's.",
    imageURL:
      "https://i.pinimg.com/736x/b0/f0/d6/b0f0d640c25c6ca1f7dc1e7098ab9f7d.jpg",
    rating: 4.3,
    stock: 60,
    color: "Xanh đậm",
    size: "L",
  },
  {
    name: "Áo len nữ",
    category: "Thời trang nữ",
    brand: "Gap",
    price: 49.99,
    desc: "Áo len nữ ấm áp từ Gap.",
    imageURL:
      "https://hips.hearstapps.com/hmg-prod/images/hbz-street-style-mfw-2018-day5-01-1519680327.jpg",
    rating: 4.0,
    stock: 55,
    color: "Hồng",
    size: "M",
  },
  {
    name: "Giày thể thao nam",
    category: "Thời trang nam",
    brand: "Nike",
    price: 79.99,
    desc: "Giày thể thao nam từ Nike.",
    imageURL:
      "https://hips.hearstapps.com/hmg-prod/images/gettyimages-924181180-1568310644.jpg?resize=980:*",
    rating: 4.6,
    stock: 45,
    color: "Trắng",
    size: "XL",
  },
  {
    name: "Đầm dự tiệc",
    category: "Thời trang nữ",
    brand: "ASOS",
    price: 99.99,
    desc: "Đầm dự tiệc lộng lẫy từ ASOS.",
    imageURL:
      "https://leoncechenal.com/wp-content/uploads/2023/08/french_fall_fashion_trends.webp",
    rating: 4.4,
    stock: 30,
    color: "Vàng",
    size: "L",
  },
  {
    name: "Balo học sinh",
    category: "Thời trang phụ kiện",
    brand: "JanSport",
    price: 29.99,
    desc: "Balo học sinh thời trang từ JanSport.",
    imageURL:
      "https://i.pinimg.com/474x/31/8c/df/318cdf4d6e784ce738cfc5dc29c1dbc9.jpg",
    rating: 4.7,
    stock: 70,
    color: "Xanh dương",
    size: "One Size",
  },
  {
    name: "Áo len nam",
    category: "Thời trang nam",
    brand: "Uniqlo",
    price: 39.99,
    desc: "Áo len nam ấm áp từ Uniqlo.",
    imageURL:
      "https://i.pinimg.com/474x/93/06/58/9306583f1dd8b6e2943a16c72eb66a1f.jpg",
    rating: 4.2,
    stock: 65,
    color: "Xám",
    size: "S",
  },
  {
    name: "Áo sơ mi nữ",
    category: "Thời trang nữ",
    brand: "Mango",
    price: 44.99,
    desc: "Áo sơ mi nữ dễ thương từ Mango.",
    imageURL:
      "https://i.pinimg.com/736x/b1/62/0d/b1620d84e8817f466e06876ba97b35de.jpg",
    rating: 4.3,
    stock: 50,
    color: "Trắng",
    size: "M",
  },
  {
    name: "Giày cao gót nữ",
    category: "Thời trang nữ",
    brand: "Steve Madden",
    price: 69.99,
    desc: "Giày cao gót nữ thời trang từ Steve Madden.",
    imageURL:
      "https://i.pinimg.com/736x/17/f8/d8/17f8d818491173e299a47342710af6e2.jpg",
    rating: 4.8,
    stock: 35,
    color: "Đen",
    size: "L",
  },
];
