export { default as Admin } from "./admin/Admin";
export { default as Login } from "./auth/Login";
export { default as Register } from "./auth/Register";
export { default as Reset } from "./auth/ResetPassword";
export { default as Contact } from "./contact/Contact";
export { default as Home } from "./home/Home";
export { default as Cart } from "./cart/Cart";
export { default as Product } from "./products/product";
export { default as NotFound } from "./notFound/NotFound";
// export { default as OrderHistory } from "./orderHistory/OrderHistory.jsx";
